version: '3.0'

services:
  # nest-api:
  #   container_name: nest
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   env_file:
  #     - ./backend/.env
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - postgres
  #   restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
volumes:
  pgdata:
