version: '3.0'

services:
  nest-api:
    container_name: nest
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx:1.19.8-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend/build:/var/www/html
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./etc-letsencrypt:/etc/letsencrypt

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./backend/pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
volumes:
  pgdata:
